### PR TITLE
Fix example workflow

### PR DESCRIPTION
**Pull request by longquanzheng**

### CODE REVIEW

**Comment by slater-ben** [comment]
My 2c (take it or leave it - I won't be offended) as someone new to Cadence trying to follow this code to get a sense of what Cadence does (which I think is the intent of this example)  is that all the extra comments in here explaining the business logic (eg " If customer cancelled their subscription during trial period, send notification email") actually make it harder to work out what Cadence is doing.

I think more useful would be something like the following:
    // sendWelcomeEmail is an activity in Cadence. It is implemented in user code and Cadence executes this activity on a worker node when needed. 
    activities.sendWelcomeEmail(customer);

    // Cadence can pause the workflow at this stage (saving it's state to the database) and will restart it when the 30 day time expires or the subscriptionCancelled event is received
    Workflow.await(Duration.ofDays(30), () -> subscriptionCancelled); 


I'm happy to go through the PR and do some more editing like this if you think it makes sense

**Comment by longquanzheng** [comment]
@slater-ben Yes, I think your comments make a lot more sense. 
Go ahead to go through it and give more suggestion, I would love to improve on this. Your comments is more helpful as you can easily think on the new users' point of view.

**Comment by longquanzheng** [comment]
@slater-ben I update updated the code with your comments, and remove also add some from me based on your suggestion. Feel free to give more suggestion.

**Comment by slater-ben** [comment]
It might be my lack of github skills but I don't seem to be able to update the branch in the PR. I've made a few changes in the attached file - both simplifying logic and adding a couple more comments.

[01-workflows.md](https://github.com/uber/Cadence-Docs/files/7471543/01-workflows.md)

**Comment by longquanzheng** [comment]
@slater-ben Thanks. Your change is even better! I like the idea of removing the trial period logic which reduce the complexity and still showing the power of it.

**Pull request merged**
